import { test, expect } from '@playwright/test'
const books = [{ id: 1, title: '夏目漱石作品集', authors: '夏目 漱石', shelf_candidates: [] }, { id: 2, title: 'こころ', authors: '夏目 漱石', shelf_candidates: [] }]
const index = { version: 1, books, topics: [{ id: 'c-language', label: 'C言語', aliases: ['C言語'], count: 3 }], coverage: { books: 2, page_count: 0, level: 0 } }
test.beforeEach(async ({ page }) => {
  await page.route('**/search-index.json', route => route.fulfill({ json: index }))
  await page.route('**/api/**', route => route.fulfill({ json: { books, total: books.length } }))
})
test('local suggestions select author and title without per-keystroke API calls', async ({ page }) => {
  const requests: string[] = []
  page.on('request', request => { if (request.url().includes('/api/books/search')) requests.push(request.url()) })
  await page.goto('/')
  const input = page.getByRole('combobox', { name: '本を検索' })
  await input.fill('夏目')
  await expect(page.getByRole('option')).toHaveCount(2)
  expect(requests).toHaveLength(0)
  await input.press('ArrowDown')
  await input.press('Enter')
  await expect(page.getByRole('heading', { name: '検索結果' })).toBeVisible()
  await input.fill('ここ')
  await page.getByRole('option', { name: 'こころ 書名' }).click()
  await expect.poll(() => new URL(page.url()).searchParams.get('q')).toBe('こころ')
})
test('topic selection opens a filtered search without requiring a title query', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('combobox', { name: '本を検索' }).fill('Ｃ言語')
  await page.getByRole('option', { name: 'C言語 テーマ' }).click()
  await expect(page).toHaveURL(/topic=c-language/)
  await expect(page.getByLabel('ジャンル・テーマ')).toHaveValue('c-language')
  await expect(page.getByText('2件ヒット')).toBeVisible()
})
test('composition and Escape preserve ordinary search', async ({ page }) => {
  await page.goto('/')
  const input = page.getByRole('combobox', { name: '本を検索' })
  await input.focus()
  await input.dispatchEvent('compositionstart')
  await input.fill('夏目')
  await input.dispatchEvent('keydown', { key: 'Enter', isComposing: true })
  await expect(input).toHaveAttribute('aria-expanded', 'false')
  await input.dispatchEvent('compositionend')
  await expect(page.getByRole('listbox', { name: '検索候補' })).toBeVisible()
  await input.press('Escape')
  await input.press('Enter')
  await expect.poll(() => new URL(page.url()).searchParams.get('q')).toBe('夏目')
})
test('late index uses the latest input and failed index never blocks submit', async ({ page }) => {
  let release: () => void = () => {}
  const gate = new Promise<void>(resolve => { release = resolve })
  await page.route('**/search-index.json', async route => { await gate; await route.fulfill({ json: index }) })
  await page.goto('/')
  const input = page.getByRole('combobox', { name: '本を検索' })
  const requested = page.waitForRequest('**/search-index.json')
  await input.fill('夏目')
  await requested
  await input.fill('ここ')
  release()
  await expect(page.getByRole('option')).toHaveCount(1)
  await expect(page.getByRole('option')).toContainText('こころ')
  await page.route('**/search-index.json', route => route.fulfill({ status: 503 }))
  await page.reload()
  await input.fill('検索')
  await input.press('Enter')
  await expect.poll(() => new URL(page.url()).searchParams.get('q')).toBe('検索')
})
test('touch selects a candidate', async ({ browser, baseURL }) => {
  const context = await browser.newContext({ hasTouch: true, viewport: { width: 390, height: 844 } })
  const page = await context.newPage()
  await page.route('**/search-index.json', route => route.fulfill({ json: index }))
  await page.route('**/api/**', route => route.fulfill({ json: { books, total: 2 } }))
  await page.goto(baseURL!)
  await page.getByRole('combobox', { name: '本を検索' }).fill('ここ')
  await page.getByRole('option', { name: 'こころ 書名' }).tap()
  await expect.poll(() => new URL(page.url()).searchParams.get('q')).toBe('こころ')
  await context.close()
})
test('filters preserve URL on pagination and back from detail', async ({ page }) => {
  await page.route('**/api/books/search?**', route => route.fulfill({ json: { books, total: 65 } }))
  await page.goto('/search?q=本&topic=c-language&author=田中')
  await expect(page.getByLabel('著者', { exact: true })).toHaveValue('田中')
  await expect(page.getByLabel('ページ数（下限）')).toBeDisabled()
  await page.getByRole('button', { name: '次のページ' }).click()
  await expect(page).toHaveURL(/page=2/)
  expect(new URL(page.url()).searchParams.get('topic')).toBe('c-language')
  await page.getByRole('button', { name: 'こころ', exact: true }).click()
  expect(new URL(page.url()).searchParams.get('author')).toBe('田中')
  await page.goBack()
  await expect(page.getByLabel('ジャンル・テーマ')).toHaveValue('c-language')
  await page.getByRole('button', { name: '条件を解除' }).click()
  await expect(page).toHaveURL(/q=/)
  expect(new URL(page.url()).searchParams.has('topic')).toBe(false)
})
